<?php
date_default_timezone_set('Europe/Moscow');
define("DCS_DBHOST","127.0.0.1");
define("DCS_DBNAME","sm24");
define("DCS_DBUSER","postgres");
define("DCS_DBPASS","3@141592");
define("DCS_COMPANY_SHORTNAME","S2B");
define("DCS_COMPANY_NAME","TIM Websystems");
define("DCS_COMPANY_FULLNAME","S2B Websystems");
define("DCS_COUNT_REC_BY_PAGE", 500);
define("DCS_EDIT_DELAY", '00:20');
define("DCS_EMPTY_ENTITY", '00000000-0000-0000-0000-000000000000');
define("DCS_EMPTY_DATE",date("Y-m-d H:i:s",mktime(0,0,0,1,1,1)));
define("DCS_EMPTY_TIME",mktime(0,0,0,1,1,1));
define("DCS_TYPE_SET",2);
define("DCS_TYPE_ITEM",3);
define("DCS_TYPE_REF",1);
define("DCS_TYPE_DOC",4);
define("DCS_TYPE_VAL",5);
define("DCS_TYPE_EMPTY",0);
define("DCS_ONE_TO_ONE",0);
define("DCS_ONE_TO_MANY",1);
define("DCS_MANY_TO_MANY",2);
define("DCS_MANY_TO_ONE",3);
define("DCS_EMPTY",-1);
define("DCS_MUSTBE_PROPERTY",1);
define("DCS_PROPS_RANK_ID",18);
define("DCS_PROPS_NAME_ID",1);
define("DCS_PROPS_ACTIVITY_ID",7);
define("DCS_PROPS_DATE_ID",8);
define("DCS_PROPS_NUMBER_ID",57);
define("DCS_PROPS_TEMPL_ID",'8422bc3b-5483-4c96-a5a2-f69b4b47c2c3');
define("DCS_PROPS_TEMPL_NAME",'PropsTemplate');
define("DCS_CS_PROPS_ID",29);
define("IT_IS_UUID","^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$");
define("DCS_UPLOAD_DIR","/upload");
define("DCS_UPLOAD_LOG","/log/upload");
define("DCS_UPLOAD_IMPORT_DIR","/upload/import");
define("DCS_UPLOAD_IMPORT_LOG","/log/import");
define("DCS_API_LOG","/log/api");
define("DCS_DENY_ACCESS",800);
define("DCS_ERROR_DB",900);
define("DCS_ERROR_SQL",910);
define("DCS_ERROR_WRONG_PARAMETER",990);
define("DCS_ERROR_UNKNOWN",999);

